# Generated by Django 4.1.3 on 2022-12-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
